/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: The Smithsonian Institution (https://sketchfab.com/Smithsonian)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/triceratops-horridus-marsh-e9c507f179ed4455aac3b208c9e6c973
Title: Triceratops Horridus Marsh
*/

import { useGLTF } from '@react-three/drei'

import MyDino from "../assets/3d/big/triceratops_horridus_marsh.glb";

const Dinosaur = (props) => {
  const { nodes, materials } = useGLTF(MyDino)
  
  return (
    <group {...props} dispose={null}>
      {/* <group rotation={[-Math.PI / 2, 0.05, 0]}> */}
        {/* <group rotation={[Math.PI / 2, 0, 0]}> */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials['default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials['default']}
          />
    </group>
  
    //   </group>
    // </group>
  )
}

useGLTF.preload(MyDino)

export default Dinosaur;